### ISSUE TITLE
How can I install this plugin?

### ISSUE THREAD

**Issue by mickdekkers** [JordanAdams/cerebro-npm#3]
It does not show up in the plugins list when I type `plugins` in cerebro.
Thanks in advance!

**Comment by JordanAdams** [comment]
Unfortunately there was an issue with Cerebro's plugin search in that it only gets the first 25 plugins. It looks like this it was fixed in [this PR](https://github.com/KELiON/cerebro/pull/194) so I would expect it'll be out in the next update of Cerebro 🙂

**Comment by lubien** [comment]
[Cerebro 0.2.7](https://github.com/KELiON/cerebro/releases) solves this issue
