### ISSUE TITLE
Use memoization and debunce

### ISSUE THREAD

**Issue by lubien** [JordanAdams/cerebro-npm#5]
Right now, every time we type a query on your plugin we make a call to NPM's API.

That means that if I type "koa" we'll call "k", "ko", "koa" requests. Let's pretend I type "koac" with the "c" as typo then I delete the "c".This will make "k", "ko", "koa", "koac", "koa" requests. Two "koa" requests.

Memoization can reuse already loaded result. Currently I'm memoizing requests for one minute in my projects just so minor problems like the above one doesn't happen.

Debounce can prevent unwanted requests (like "k", "ko") while user is typing.

If you don't mind I can make a PR

[p-debounce](https://github.com/sindresorhus/p-debounce/blob/master/readme.md)
[memoize](https://github.com/KELiON/cerebro-tools#memoize)
[example](https://github.com/lubien/cerebro-hex/blob/master/src/index.js#L17-L21)

**Comment by JordanAdams** [comment]
Sounds good to me. If you're happy to PR this, feel free 🙂 

_Awesome work on cerebro-hex, I was planning on building that too_ 😄

**Comment by lubien** [comment]
Added on #4 

I didn't knew you use Elixir too btw ^^
